### ISSUE TITLE
[FR] Save chat history

### ISSUE THREAD

**Issue by sad-zero** [sad-zero/llm-chatbot-for-messengers#11]
# Goal
- Use chat histories
- Save chat histories in memory or DB

---
## Reason
- Manage users and conversations

---
## TODO
- [ ] Store user informations
- [ ] In memory chat history
- [ ] Persistant chat history

---
