### ISSUE TITLE
[FR] Refactor based on Future design

### ISSUE THREAD

**Issue by sad-zero** [sad-zero/llm-chatbot-for-messengers#32]
# Goal

- Refactor project.

---
## Reason
- Redisign

---
## TODO
- [ ] Refactor domain layer
- [ ] Refactor Messenger IF layer
- [ ] Refactor Infra layer
- [ ] Refactor IoC Container
---
